name: GitHub Power Ubuntu RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Full Ubuntu Desktop & XRDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp

      - name: Configure XRDP & Set Password
        run: |
          echo "runneradmin:123456" | sudo chpasswd
          echo xfce4-session > ~/.xsession
          sudo sed -i 's/max_bpp=32/max_bpp=16/g' /etc/xrdp/xrdp.ini
          sudo service xrdp restart

      - name: Install Cloudflare Tunnel
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflare Tunnel
        run: |
          cloudflared tunnel --url tcp://localhost:3389
          
